# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#title: Candyce Douglas
#email: "candyce.douglas@gmail.com"
#description: >- # this means to ignore newlines until "baseurl:"
#  A Bootstrap 4 start up project for Jekyll and Github Pages

#url: "https://c-douglas.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#baseurl: "/c-douglas.github.io" # the subpath of your site, e.g. /blog
#twitter_username: jekyllrb
#github_username:  c-douglas
#repository: "c-douglas/c-douglas.github.io"

# Choose one of the options: Style will be applied only after restarting the build or serve.
theme_skin: berry     # blue turquoise green berry orange ceramic
chrome_mobile_color: # use hex colors (ex:#1976d2) or leave empty for no color for chrome mobile searchbar

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# A list of the pages to display in the navigation bar
header_pages:

# Build settings
compress-site: no

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  #- node_modules
  #- update_boostrap.sh